name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Install SwiftLint
      run: brew install swiftlint

    - name: Install Dependencies
      run: make install-tools

    - name: SwiftLint
      run: make lint

    - name: Build
      run: make build

    - name: Run tests
      run: make test
