name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Install Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "6.0"

    - name: Check Swift version
      run: swift --version

    - name: Select Xcode
      run: |
        XCODE_VERSION=$(xcodebuild -version | grep '^Xcode\s' | awk '{print $2}')
        echo "Using Xcode version: $XCODE_VERSION"
        sudo xcode-select -s /Applications/Xcode.app

    - name: Install SwiftLint
      run: brew install swiftlint

    - name: Install Dependencies
      run: make install-tools

    - name: SwiftLint
      run: make lint

    - name: Build
      run: make all

    - name: Run tests
      run: make test-all

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults/
